assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/components
  js_compressor: ~
  css_compressor: ~
  autosize: false
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false
  version: 1
